# Generated by Django 4.0.2 on 2022-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('key', models.CharField(max_length=10)),
                ('drivers', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
    ]
