# Generated by Django 4.0.2 on 2022-02-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_number',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number',
            field=models.CharField(default='Not assigned', max_length=3),
        ),
    ]
