# Generated by Django 4.0.2 on 2022-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0002_job_job_number_alter_truck_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
